### ISSUE TITLE
Runs with multiple videos aren't handled

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplitOne#106]
In [this one case](https://www.speedrun.com/smo/run/zg7nwwvz) there's a link to a guy's channel as the first video and the actual run video as the second link. That's unfortunate as we only handle one video URL atm, so we instead show the link to his channel:

![https://i.imgur.com/lLuDfXO.png](https://i.imgur.com/lLuDfXO.png)

We should probably show all videos.

**Comment by wooferzfg** [comment]
How do you provide multiple video URLs on speedrun.com?

**Comment by CryZe** [comment]
speedrun.com scans the comment for additional URLs.

**Comment by wooferzfg** [comment]
Here's another example: https://www.speedrun.com/tww/run/kz5105gm

I think it would make sense to just handle embeds the same way that speedrun.com does (if a video is linked in the comment, display an embedded version of it there).

**Comment by wooferzfg** [comment]
Do we even want this? With the changes in https://github.com/LiveSplit/LiveSplitOne/commit/191b6d621a32dac2fbe910c9dc50a03509d652e0, we always show the main video, which IMO is good enough. Showing embeds for every video in the comments would sometimes result in certain runs taking up way too much space on the leaderboard.

**Comment by CryZe** [comment]
Alright, let‘s close this then.
