### ISSUE TITLE
The Side Bar doesn't work on iOS anymore.

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplitOne#129]
Gotta love JS libraries.

**Comment by CryZe** [comment]
The feature seems to have been removed: https://github.com/balloob/react-sidebar/issues/67

Their reasoning is that it wasn't really working anyway with the browser also going back a page by swiping, which is true, except for when you pin LSO to the home screen. Well, I guess we wanted to get rid of the sidebar in the long run anyway.

**Comment by wooferzfg** [comment]
Can we close this since you can just open the sidebar by pressing on the button for it now?

**Comment by CryZe** [comment]
Yeah
