### ISSUE TITLE
Unable to close the Electron app if run has been modified.

### ISSUE THREAD

**Issue by TheEssenceOfDarkness** [LiveSplit/LiveSplitOne#136]
https://github.com/LiveSplit/LiveSplitOne/blob/c9ed2476edab0b7a711129dfe114c8df6f17737e/src/ui/LiveSplit.tsx#L94

Unlike most web browsers, Electron does not display a close prompt here, and instead just prevents you from closing the window. 

Tested on both the Windows (using wine), and Linux version of Electron.

Edit: as a side note i really need to stop forgetting entire words in my titles

**Comment by CryZe** [comment]
Well it all comes down to how much we even want to have an electron version. It's still unclear what Desktop framework we are going to use, electron is just one of many choices. Although we could definitely have an electron version beside that.

**Comment by TheEssenceOfDarkness** [comment]
> Well it all comes down to how much we even want to have an electron version. It's still unclear what Desktop framework we are going to use, electron is just one of many choices. Although we could definitely have an electron version beside that.

I chose to get an Electron build made and working because I saw that there was initial support for that added recently. It works pretty well in a dev environment, so I figured I could help get the bulk of the tools configured for a proper build.

> Feel free to fix any bugs in the electron version you encounter though.

I'll probably fix this and a few other issues I encounter in #135 if that's fine with you. I want to avoid making a separate PR for everything I end up fixing.
