### ISSUE TITLE
error: enable either wasm_bindgen or stdweb feature

### ISSUE THREAD

**Issue by zsty** [LiveSplit/LiveSplitOne#138]
At a guess, this is the build script or livesplit core (or both)
running `cargo build` in livesplit-core has no issues, and doesn't fix anything

The error occurs while compiling rand_os as far as I can tell.

Just a note that I have _zero_ experience with rust.

**Comment by zsty** [comment]
Just an added note: grabbing a wasm from the livesplit-core release doesn't seem to work, saying "Can't load livesplit-core disable adblock" etc. Webpack spits out a lot of Babel errors, though I'm pretty sure those are unrelated react deprecation errors

**Comment by CryZe** [comment]
You are right, it seems that the new rand versions require the use of either of those binding generators, ... except those are very opinionated to the point where they don‘t fit our use case. And people often pretend that this use case isn‘t relevant and you should be using wasm-bindgen, but that just doesn‘t work for us, so this is kind of a constant struggle to remind people that they have to keep this use case in mind.
