### ISSUE TITLE
Adding Video to Livesplit?

### ISSUE THREAD

**Issue by SryImLowskilled** [LiveSplit/LiveSplitOne#139]
Hi,
i have a small problem, i searched google and some posts in here, but nothing worked.

I want to add a PB Video to my Livesplit. while searching for answers i discovered i need to use VLC 2.2.1 64 Bit (yes i do have 64 bit Windows :P ) Version and the Plugin ActiveX installed. Thats what i did. 
The mp4 i want to be seen is playable in VLC and i can browse for it. However, whenever i start my Timer, the only Image i see is the VLC Logo.
Im using Livesplit 1.7.6 as well, if it matters.

any suggestions? thanks :)

edit : does it work on windows 10?

**Comment by MutantAura** [comment]
I never got it to work in livesplit but my work around was just to add the video as an OBS source then hide and unhide it with a hotkey. Check the setting to make it start everytime it loads and you're golden. 
I use any random key to start it and my "end timer" key to stop it. DO NOT use the "split" key to "start" the video thought cause it just starts again XD

**Comment by hallcristobal** [comment]
Folks: 
The functionality you're looking for is for normal  [LiveSplit](https://github.com/LiveSplit/LiveSplit) ,
submit your issue there and you might get better results. This repo is for the rewrite that is currently on going.
