### ISSUE TITLE
[electron] globalShortcut

### ISSUE THREAD

**Issue by plexigras** [LiveSplit/LiveSplitOne#155]
https://github.com/electron/electron/blob/master/docs/api/global-shortcut.md

**Comment by CryZe** [comment]
I don‘t think we need this, as the original idea was indeed to use Electron on the Desktop, but livesplit-core brings its own implementation for the hotkeys across the platforms. However now we don‘t even intend to use Electron at all anymore for the Desktop versions. Someone might attempt to bring the web version to the desktop via electron, but that‘s not what we are intending to go for, for the official versions.

**Comment by plexigras** [comment]
oh okay.

> However now we don‘t even intend to use Electron at all anymore for the Desktop versions. Someone might attempt to bring the web version to the desktop via electron, but that‘s not what we are intending to go for, for the official versions.

what are the plans for linux support?

**Comment by CryZe** [comment]
The Desktop version works perfectly fine on Windows, macOS and Linux (also iOS and Android (haven‘t tested Android yet though))

**Comment by plexigras** [comment]
you mean the browser version?

**Comment by CryZe** [comment]
No, there is a separate desktop version. It's not public yet as it's still fairly experimental.

**Comment by plexigras** [comment]
oh thats good to hear

**Comment by plexigras** [comment]
for anybody who is going to come across this in the future this is how i got it to work :smile: 

```diff
diff --git a/src/electronMain.js b/src/electronMain.js
index 6d7220c..38ff2d6 100644
--- a/src/electronMain.js
+++ b/src/electronMain.js
@@ -1,5 +1,5 @@
 // Modules to control application life and create native browser window
-const { app, BrowserWindow } = require("electron");
+const { app, BrowserWindow, globalShortcut } = require("electron");
 const path = require("path");
 const url = require("url");
 
@@ -9,6 +9,7 @@ let mainWindow;
 
 function createWindow() {
     // Create the browser window.
+
     mainWindow = new BrowserWindow({
         width: 800,
         height: 800,
@@ -25,6 +26,10 @@ function createWindow() {
         slashes: true,
     }));
 
+    globalShortcut.register('D', () => {
+        mainWindow.webContents.send('keydown', 'KeyW')
+    })
+
     // Emitted when the window is closed.
     mainWindow.on("closed", function() {
         // Dereference the window object, usually you would store windows
diff --git a/src/livesplit.ts b/src/livesplit.ts
index caa7532..7fc5789 100644
--- a/src/livesplit.ts
+++ b/src/livesplit.ts
@@ -104,6 +104,11 @@ export async function load(path?: string) {
                     dealloc({ ptr, len });
                 };
                 window.addEventListener("keypress", listener);
+                electron && electron.ipcRenderer.on('keydown', (_, code) => {
+                    const { ptr, len } = allocString(code);
+                    instance().exports.HotkeyHook_callback(ptr, len - 1, handle);
+                    dealloc({ ptr, len });
+                })
                 handleMap.set(handle, listener);
             },
             HotkeyHook_drop: function (handle: number) {
diff --git a/webpack.config.js b/webpack.config.js
index 30d9e10..cdf054b 100644
--- a/webpack.config.js
+++ b/webpack.config.js
@@ -3,6 +3,7 @@ module.exports = (env, argv) => {
     const CopyWebpackPlugin = require("copy-webpack-plugin");
     const WebpackPwaManifest = require("webpack-pwa-manifest");
     const CleanWebpackPlugin = require("clean-webpack-plugin");
+    const DefinePlugin = require("webpack").DefinePlugin;
     const path = require("path");
 
     const basePath = __dirname;
@@ -52,6 +53,9 @@ module.exports = (env, argv) => {
                     },
                 ],
             })] : []),
+            new DefinePlugin({
+                electron: isElectron ? 'require("electron")' : 'undefined'
+            }),
             new CopyWebpackPlugin([
                 { from: "src/livesplit_core.wasm", to: "livesplit_core.wasm" },
                 ...(

```

**Comment by plexigras** [comment]
and this is the keybinding reference for electron

https://electronjs.org/docs/api/accelerator

**Comment by plexigras** [comment]
@CryZe i would love to contribute to / try / test this new linux compatible version.

**Comment by rosshadden** [comment]
@plexigras the experimental project is https://github.com/CryZe/livesplit-one-desktop . It doesn't have as much functionality as the web version yet but works great on Linux, and has global hotkey support built-in. I started using it yesterday and will likely end up contributing to it before long.
