### ISSUE TITLE
Hotkeys cannot be reassigned in Firefox on macOS

### ISSUE THREAD

**Issue by slingshotocelot** [LiveSplit/LiveSplitOne#160]
Reassigning hotkeys from the Numpad defaults fails in Firefox. Clicking on the key assignment button animates, but the key name does not turn red as it does in Chrome and pressing a key has no effect.

[Screen recording](https://i.imgur.com/1lrwQE2.mp4)

(Tested with Firefox 67.0, Chrome 74, macOS 10.13.6)

**Comment by CryZe** [comment]
Can you check if there are any JavaScript errors? That's pretty crazy.

**Comment by slingshotocelot** [comment]
No, I'm not seeing anything in the console.

**Comment by hallcristobal** [comment]
It seems that this is a confirmed inconsistency with MacOS and web browsers. The Event that we handle is not fired at an Element level in Firefox meaning that React cannot handle it.  
Relevant issue: https://github.com/facebook/react/issues/12993

**Comment by CryZe** [comment]
We probably want to not use the button's focus and instead do an invisible whole page overlay that prevents clicking anywhere else. Once you do, we consider that losing the focus and stop recording the hotkeys. I guess we can also still react to the button losing the focus for browsers that support it.
