### ISSUE TITLE
Timer still running at last split

### ISSUE THREAD

**Issue by danxensen** [LiveSplit/LiveSplitOne#167]
When I finish a run by advancing my splits to the end and then try to export my splits to splits.io, it doesn't have my new times. If I try to do actions like edit the splits I receive the message "You can't edit your run while the timer is running" even though I've clearly reached the end and the timer is no longer active. I couldn't figure out what to do so I had to manually edit my .lss to upload my latest PB, which was a pain.

This appears to be similar to issue #71, although that issue was supposedly fixed a year ago and I'm encountering problems now. Is it possible that I'm not "ending" my run correctly or is there still something broken?

**Comment by CryZe** [comment]
Did your run beat the Personal Best? If not, then the Personal Best will be uploaded instead. The original LiveSplit has a message that asks if you want to save / upload the new run as the Personal Best instead, but that's not implemented yet.

**Comment by danxensen** [comment]
If you're talking about the "Compare Against" setting, yes it's set to Personal Best. I don't think I currently have a key bound for reset, but that's what the X button does right? So if I hit that when I finish a run I can then upload my new splits?

**Comment by CryZe** [comment]
I'm not talking about "Compare Against". I'm talking about your record. If your new run does not beat your record, then the record is uploaded instead. Yes, you probably want to reset first regardless, which is what the X button does. Whatever state you are in afterwards is what will be uploaded.

**Comment by danxensen** [comment]
Ok.. I was thinking that I could upload my splits regardless of better/worse since splits.io has that cool graph stuff. I guess it's fine if it only uploads better splits. It's probably working then, so I just need to try resetting next time I run. Thanks

**Comment by CryZe** [comment]
The graph should show the worse splits (and all the other history) should show the new / worse runs regardless. However the list of splits are designed to show the Personal Best. We'll have an option to save the current run as the Personal Best, but maybe that's something to think about for splits.io too (They have access to the latest run, so maybe they could show that).

**Comment by CryZe** [comment]
Alright, I checked the code again and it was indeed wrong. When the run is ended it should save it as if you reset it, but that's not what happened. I'm pushing a fix now.

**Comment by danxensen** [comment]
Oh cool, thanks! So I don't *have* to reset at the end, but it may still be a good habit.

**Comment by CryZe** [comment]
Yeah exactly :D
