### ISSUE TITLE
Auto Splitter Support

### ISSUE THREAD

**Issue by AceDolphin** [LiveSplit/LiveSplitOne#176]
So, I know this is probably a long ways off or not happening, but are there plans on bringing auto splitter support to live split one. Thanks : )

**Comment by CryZe** [comment]
Yeah it'll definitely have auto splitting (the Desktop versions, not the web version). There's been a lot of prototyping and experimenting going on, but we are slowly getting somewhere.

**Comment by CryZe** [comment]
I'm going to close this in favor of the issue in the Desktop version of LiveSplit One: https://github.com/CryZe/livesplit-one-desktop/issues/11
