### ISSUE TITLE
Implement a Run Selection View

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplitOne#189]
We probably want to have a view where we move all the current options for modifying the run to. Basically there you would have a view of all your splits (so you'd have multiple, instead of just one). You can then choose to edit them, copy them, export them, import some, download them from splits.io or upload them, and so on. So basically all the run specific options in the sidebar would move into this view.

**Comment by CryZe** [comment]
This is what we envisioned for a "LiveSplit 2.0" a long time ago. I believe the Run Selection View should still roughly look like this:

![https://i.imgur.com/TteZz6A.png](https://i.imgur.com/TteZz6A.png)

**Comment by CryZe** [comment]
I think this is something we should focus on next.

**Comment by wooferzfg** [comment]
@CryZe Thoughts on this layout?

![splits_view_mockup](https://user-images.githubusercontent.com/8262173/76722543-0ccc2880-6712-11ea-876e-ac82e3f504ce.png)

**Comment by CryZe** [comment]
We'd want to have edit, export, save, and co. for the other splits as well. But yeah this is mostly how it should look like I guess. Though I definitely wanted grouping by game, but that's not overly important for an initial implementation.

**Comment by CryZe** [comment]
I'll mostly focus on implementing the indexed db stuff today and I'll open up a PR later where you could start doing the UI changes if you want to (I already made some minimal changes, but no CSS or anything).
