### ISSUE TITLE
Try using the State objects instead of going through JSON

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplitOne#22]
livesplit-core provides all the component states as objects that you can traverse. Exposing their states as JSON was quite a fun idea, as that can be directly converted into a JavaScript object. However serializing into JSON and back into a JavaScript object is potentially more expensive than using the state objects directly. So we should try using those and see if it's faster.

**Comment by CryZe** [comment]
This however would mean that we can't just get JSON from some REST API anymore, which is something we would want to do though. So if we try this approach, we also need a solution for the REST APIs.

**Comment by CryZe** [comment]
Tracked in livesplit-core now as well: https://github.com/LiveSplit/LiveSplitOne/issues/22

**Comment by wooferzfg** [comment]
@CryZe @TheEssenceOfDarkness Since https://github.com/LiveSplit/livesplit-core/pull/289 got merged, are we now able to get this working in LSO?

**Comment by CryZe** [comment]
Yes, no, maybe. It's probably still missing a lot, but we can definitely start exploring this. Alternatively we can try https://crates.io/crates/serde-wasm-bindgen to directly serialize the state to a javascript object instead of a json string that gets deserialized on JavaScript's side.

**Comment by TheEssenceOfDarkness** [comment]
>It's probably still missing a lot, but we can definitely start exploring this.

Yeah that PR was just the minimum needed to make this even viable. A lot of the getter functions LSO would need are not implemented yet so someone would need to add those.

**Comment by CryZe** [comment]
#286 also addresses this in a way. We don't need the state objects at all on JavaScript's side if we do the DOM modifications from Rust directly.

**Comment by CryZe** [comment]
I'm closing this in favor of #286. During some experimentation there I noticed that every single call between WASM and JS is quite expensive, so funnily the solution of passing objects by serializing through JSON is actually faster in the end than using state objects. However what can indeed be optimized is not moving that much data over in the first place and instead only move the data over that represents actual changes. But that's exactly what is being explored over there. So there's nothing left to do here.
