### ISSUE TITLE
Turn livesplit-core into its own package

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplitOne#231]
livesplit-core should be its own package that just gets imported like any other package. The idea is to make it separate enough that we can publish it to npm whenever we do a new release of livesplit-core. In general I'd like to start modularizing the codebase a bit more, so that we can possibly move the "layout renderer" into its own package as well. This would ensure that all the layout's CSS is properly separated out from the rest of the UI and it allows other experimentation such as a Twitch Extension where you may not want everything.

**Comment by wooferzfg** [comment]
The layout rendering is already pretty separate from the UI. The only things that are currently shared are:
- livesplit-core
- The util functions
- The imported fonts (Fira, timer, Roboto)
- A few lines of css in `main.scss`

I think we just need to either extract or duplicate each of these components, and then we can separate everything really easily.

**Comment by CryZe** [comment]
Yeah the only hard part is to ensure nothing gets duplicated in the end, and the package works on its own despite using a bunch of non-JS (SCSS, TypeScript, ...)

**Comment by CryZe** [comment]
While it's not a full npm package, the canvas renderer allowed me to essentially host a full LSO in just a few lines in a completely separate codebase, which is essentially what this issue was intended for

![image](https://github.com/LiveSplit/LiveSplitOne/assets/1451630/afb4e18b-8a3f-448f-a26f-e63e778bf4ee)
