### ISSUE TITLE
gh-pages does not work anymore

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplitOne#232]
Apparently we are not publishing anything to the website anymore, despite creating new commits to the gh-pages branch.

In the settings it also says:
> Your site is having problems building: Page build failed.

**Comment by CryZe** [comment]
Looks like the `secrets.GITHUB_TOKEN` doesn't have the rights to trigger a gh-pages build?!

https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/m-p/27454/highlight/true#M302

**Comment by wooferzfg** [comment]
This should work if we just use a custom token like I originally did in my PR.

**Comment by CryZe** [comment]
Yeah, this is so stupid.

**Comment by CryZe** [comment]
Resolved in https://github.com/LiveSplit/LiveSplitOne/commit/27c45166cd9461c0c3a21c5257592415d17f0309
