### ISSUE TITLE
Use a dropdown instead of arrows for switching between comparisons

### ISSUE THREAD

**Issue by wooferzfg** [LiveSplit/LiveSplitOne#233]
We have 9+ different comparisons, and having to use arrows to switch between them is pretty unintuitive. We should definitely still keep the hotkeys for switching between comparisons, but the comparison selection in the sidebar should be a dropdown menu.

**Comment by CryZe** [comment]
I'll mark this as iOS because on iOS the arrows aren't even properly fitting into the sidebar and flow into the new line. So the current implementation is basically "broken" for iOS atm (though this should be an easy fix via grid or flexbox, but idk if we want to do that when we want to replace the whole thing anyway).

**Comment by wooferzfg** [comment]
For this, we'll need to:
- Expose `Run.comparisons` in the C API so that we have a way to get a list of all the comparisons.
- Add a method to `Timer` that allows us to set the current comparison by passing in a string.
- Update LiveSplit One to show a dropdown with all the comparisons instead of arrows.

**Comment by wooferzfg** [comment]
It would also be useful to show a dropdown for choosing a comparison override in the settings.

**Comment by CryZe** [comment]
I believe I want lsc to just generically define comboboxes (i.e. it just returns a list of options for a setting), so while it would technically be useful there, lsc can just fill the list by itself, in this case.

**Comment by CryZe** [comment]
Whoops, forgot to auto close it. This is done.

**Comment by wooferzfg** [comment]
The PR was https://github.com/LiveSplit/LiveSplitOne/pull/911
