### ISSUE TITLE
Loading the Default Layout

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplitOne#234]
So far there's not really a way to load the default layout again. We haven't added this to the sidebar because it already was very cluttered. With the layout submenu, we can nicely introduce this now.

I forgot if we have "default run" in the original LiveSplit, but if we do, we may want that as well.

**Comment by wooferzfg** [comment]
We don't have a "default run" option in the original LS, but we have "Close Splits", which switches you to the default run and puts you in timer only mode (which pretty much means that your splits never update after you finish a "run"). We haven't made any plans to have timer only mode in LSO/livesplit-core yet though.
