### ISSUE TITLE
Introduce a way to stop the background networking

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplitOne#238]
This came up for the original LiveSplit where people don't want us to communicate with SRL, speedrun.com and co. in the background. We should have some kind of Offline Mode for LiveSplit One eventually. It's unclear if this should be individual settings for the various websites / kinds of communication and / or just an offline mode.

I don't think we should start working on this before we are doing all the networking in livesplit-core, as that likely is just going to cause unnecessary conflicts.

I guess we could even adjust the UI to not show any splits.io, speedrun.com, connect to server and co. such that it becomes much more of a "LiveSplit Lite" that we wanted at some point.

**Comment by TheEssenceOfDarkness** [comment]
Atomic clock sync should *definitely* be its own setting because there are plenty of cases where someone doesn't want background communication with speedrun.com and the likes but still wants to maintain accurate timing.
