### ISSUE TITLE
The layout should use the browser width if it's small enough

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplitOne#240]
This is specifically meant for mobile where we probably want to remove the top margin and fill the whole width of the phone. This would heavily improve the experience on mobile.

Additionally we may want to detect OBS browser source and always activate the same mode then.

**Comment by wooferzfg** [comment]
Do we want to disable resizing the layout on mobile too? Also, what's the best way to detect that it's an OBS browser source?

**Comment by CryZe** [comment]
Yes, if the window width is small enough, we disable the possibility to resize manually and just take the full width. And OBS browser source may be able to be detected via the user agent or something.

**Comment by wooferzfg** [comment]
Apparently we can use this: https://github.com/obsproject/obs-browser/blob/master/README.md#get-browser-plugin-version
