### ISSUE TITLE
Create visual regression tests for the layout renderer

### ISSUE THREAD

**Issue by wooferzfg** [LiveSplit/LiveSplitOne#243]
It would be nice to have visual regression testing for rendering the layout, similar to the rendering tests in livesplit-core.

- We'd need a way to render an image of the layout based on layout state data. The easiest approach that I could think of would be to start a server that renders the layout, use Selenium to open a browser to that page, and take a screenshot of it. There's also the concern that everyone uses a different OS and browser, but Docker would be a solution for that. Ideally, we could test Chrome and Firefox (and maybe some other browsers as well? not sure).
- There's lots of good libraries for image comparison. We could use [imghash](https://www.npmjs.com/package/imghash) and [pixelmatch](https://www.npmjs.com/package/pixelmatch).

**Comment by wooferzfg** [comment]
I was able to get a prototype of this running here: https://github.com/wooferzfg/LiveSplitOne/pull/3

The biggest issue right now is that font rendering is different on Ubuntu vs. Windows, which causes the screenshots not to match. Some potential ideas:
- We could run these tests in Docker so that you could easily match the environment that GitHub Actions is running in, but that's a pain to get running in Windows since [Docker Desktop requires Windows 10 Professional](https://hub.docker.com/editions/community/docker-ce-desktop-windows).
- We could [upload artifacts](https://github.com/marketplace/actions/upload-artifact) of the screenshots from GitHub Actions and cache the screenshot files so that we can persist them between builds. You would still have to rely on the CI to debug failures if you're on Windows, but it would at least provide some useful info.

**Comment by CryZe** [comment]
Yeah I guess it's fine if at least initially we only run these tests on CI.
