### ISSUE TITLE
Settings page sometimes lets you (temporarily) set the same hotkey for multiple buttons

### ISSUE THREAD

**Issue by wooferzfg** [LiveSplit/LiveSplitOne#251]
I'm always pressing Numpad 4 in this video:

![L766DphXiq](https://user-images.githubusercontent.com/8262173/74596115-715f6f00-5010-11ea-9a70-981a680a0260.gif)

This only seems to happen for certain combinations of keys?

**Comment by CryZe** [comment]
It's a livesplit-core bug. The order up there didn't match the order down there (because I think we reordered them a bit at some point) and toggle timing method was missing up there.

![https://i.imgur.com/9B3HeB6.png](https://i.imgur.com/9B3HeB6.png)
