### ISSUE TITLE
Showing the timer in its own window

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplitOne#254]
There should be a way to pop out the timer into its own window that just shows the timer (not even the controls below). This would make it easier to window capture it and is closer to how the original LiveSplit behaves, where you can just arbitrarily move and resize the window and *it just works*.

We may need the arbitrary vertical resizing first: #46

**Comment by CryZe** [comment]
Though that makes me wonder if we could do arbitrary positioning with dragging in the normal view as well.

**Comment by adRichter** [comment]
This would also make an easy window capture with OBS possible!

**Comment by CryZe** [comment]
This is a duplicate of #768 for the most part. Arbitrary resizing is a thing now.
