### ISSUE TITLE
Roboto font isn't cached by the Service Worker

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplitOne#265]
![https://i.imgur.com/DCH3YzY.png](https://i.imgur.com/DCH3YzY.png)

It's hosted on Google. Either we explicitly cache it, or just host it ourselves. Keep in mind that the woff2 at the bottom of the screenshot also needs to be cached.

**Comment by CryZe** [comment]
I'm also wondering if we want that font anyway. The native renderer doesn't use it. We just need to monospace Fira (there's some CSS that forces a monospace number layout).

**Comment by wooferzfg** [comment]
Specifically, `font-variant-numeric: tabular-nums;`
