### ISSUE TITLE
Hide, remove, or fix connecting to a websocket server

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplitOne#275]
The problem is that we are using https and that prevents you from connecting to anything that's not https. So you can't easily run a websocket server locally and connect to it. And so far this roughly uses the server protocol from the original LiveSplit (though kind of in reverse, as the client and the server in a way are swapped). It does not speak the new synchronization protocol that we want to build. Considering it also plays a prominent role in our sidebar at the moment, this is mostly just "wasting valuable space", because of how unusable it is at the moment. So I feel like we either should look into making it more usable somehow, move it into the settings menu, or just get rid of it entirely for now, as the synchronization protocol most likely will supersede it anyway.

**Comment by wooferzfg** [comment]
For the synchronization protocol, will we be connecting to external servers (like Splits.io for example) instead of a local server?

**Comment by CryZe** [comment]
Yeah, though you can probably still specify a custom URL, so it could still be a local one, as long as you figure out how to deal with https (or there's some workaround).

**Comment by CryZe** [comment]
Looks like people are really confused by this. They are now trying to connect the OBS plugin and the original LiveSplit to the Web LSO. We really need to get rid of this (maybe at least move it to the settings instead of this prominently in the sidebar).

**Comment by DarkRTA** [comment]
> maybe at least move it to the settings instead of this prominently in the sidebar
Eh, I think we should just outright remove this. Any theoretical use case this currently has will be better done with LiveSplit One Desktop, and I don't know of anyone who's currently using this.

**Comment by CryZe** [comment]
I believe @thecodewarrior is using it though. But yes, I would otherwise completely remove it for now.

**Comment by DarkRTA** [comment]
Apparently they are using it for a Celeste auto splitter.

https://github.com/thecodewarrior/SwiftSplit

**Comment by thecodewarrior** [comment]
At the moment the websocket is the only way I'm aware of to create an autosplitter for macOS, so I would prefer it stay in. However, if it were replaced with something better that filled the same role I would gladly update SwiftSplit to use it.

**Comment by DarkRTA** [comment]
> At the moment the websocket is the only way I'm aware of to create an autosplitter for macOS, so I would prefer it stay in. However, if it were replaced with something better that filled the same role I would gladly update SwiftSplit to use it.

When livesplit/livesplit-core#176 is finished, it will much better fill this role than a completely undocumented WebSocket API. I see you've actually responded to that issue and have shown interest in helping on the macOS side of things so now might be a good time to start working on that :)

**Comment by thecodewarrior** [comment]
Update on the SSL issue. I can't use `wss://`, but I can use `ws://` without issue, but only in Firefox/Chrome. Safari is stricter about localhost and doesn't let it connect.

**Comment by CryZe** [comment]
Ah I heard that Firefox supposedly changed their policy towards localhost. Seems like Chrome might've done the same. Well if that's true, then that changes everything.
