### ISSUE TITLE
Desktop version early access

### ISSUE THREAD

**Issue by TurtleTony** [LiveSplit/LiveSplitOne#276]
Scrolling through other issues it appears to me that there is work being done on desktop versions for linux etc. However to my awareness they aren't available publicly yet.
Is there any chance to get access to these early dev builds? I would love to use LiveSplitOne on linux but without the ability for global hotkeys I feel unable to use it effectively.

**Comment by DarkRTA** [comment]
There aren't any publicly available binary releases at the moment but it is possible to build it yourself as the code is publicly available.

https://github.com/CryZe/livesplit-one-desktop

Keep in mind that its not documented well right now and that it requires you to manually edit a config file. Don't expect to get very much support either.

**Comment by TurtleTony** [comment]
Ah I was unaware that this would be in a different repository. Thank you for pointing that out
