### ISSUE TITLE
Add an About dialog

### ISSUE THREAD

**Issue by hallcristobal** [LiveSplit/LiveSplitOne#28]
A simple About dialog to show copyright, creators and a link to the GitHub repo, similar to LiveSplit's.

**Comment by wooferzfg** [comment]
To list creators, we could potentially query the GitHub API and list the contributors for [LiveSplit One](https://api.github.com/repos/LiveSplit/LiveSplitOne/contributors) and [livesplit-core](https://api.github.com/repos/LiveSplit/livesplit-core/contributors).

**Comment by CryZe** [comment]
I don't think we want to query anything at runtime. People already complained in the original LiveSplit that we are querying too many APIs in the background. So I'd bake this information in at compile time.
