### ISSUE TITLE
Layout width is not preserved when switching to the mobile layout and back

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplitOne#336]
This probably regressed during #328

**Comment by wooferzfg** [comment]
Do you have a video? I'm not able to reproduce this.

**Comment by CryZe** [comment]
![https://i.imgur.com/fRQByHW.gifv](https://i.imgur.com/fRQByHW.gifv)

**Comment by wooferzfg** [comment]
Ah, the issue here is that the width it uses when going back to the desktop layout is whatever was stored when you first loaded the page rather than the most recent stored width. I'm not sure if that's a regression, but I'll look into a fix.
