### ISSUE TITLE
Empty columns cause other columns not to be shown

### ISSUE THREAD

**Issue by sobolews** [LiveSplit/LiveSplitOne#346]
Hi, thank you for creating this tool for all platforms!

I have a third column showing an extra comparison time, with the settings:

Start With: Comparison Time
Update With: Dont Update
Update Trigger: Contextual
Comparison: [comparison name]

When I do the run, the extra comparison column only displays the comparison time for each split when I reach that split. Is there any way to have the comparison times all displayed from the start of the run?

**Comment by wooferzfg** [comment]
Could you be more clear about what behavior you actually want? The settings you listed will show the comparison's times for each split, independent of what split you're on.

To demonstrate:

![Screenshot_20200428-222244_Chrome](https://user-images.githubusercontent.com/8262173/80558145-e0592c80-899e-11ea-9b34-7e45fcce2ce7.jpg)


![Screenshot_20200428-222231_Chrome](https://user-images.githubusercontent.com/8262173/80558138-dafbe200-899e-11ea-8de2-6ae2c89ecb27.jpg)

**Comment by sobolews** [comment]
I played with this a bit more, and I found that the issue actually depends on which column is the extra/third column. When I set the Extra comparison as the third (leftmost) column, it doesn't display the split times until I start that split:

![rightmost-pb](https://user-images.githubusercontent.com/6841705/80558737-9cfbbf80-8998-11ea-8d34-72dc1de7ac1d.png)



However if I set the Extra comparison to be the first (rightmost column), it displays correctly but then the PB column has the same issue, where it doesn't display until I reach that split:

![rightmost-extra](https://user-images.githubusercontent.com/6841705/80558791-c61c5000-8998-11ea-82ed-cf973a567a85.png)

Here is what my test splits look like for reference:
![test-splits](https://user-images.githubusercontent.com/6841705/80558901-24493300-8999-11ea-999c-cf408b703819.png)

**Comment by sobolews** [comment]
Another couple data points:

If I order those columns, from right to left, as +/-   PB   Extra, then everything displays correctly.

If I order them, from right to left, as PB Extra +/-, then both PB and Extra don't display.

My guess is that the +/- column with the "Start With: Empty" setting is somehow messing up each column to the left of it.

**Comment by wooferzfg** [comment]
Ah, I see what's happening. Thank for the bug report!
