### ISSUE TITLE
livesplit-core bindings generated with wasm-bindgen don't work anymore

### ISSUE THREAD

**Issue by JamesDalboth** [LiveSplit/LiveSplitOne#349]
After running the install instructions on both Firefox and Google Chrome I get browser not support webassembly / adblock error. I'm using modern versions of these brownsers and not using adblock so strange.

Interestingly in the console I get a lot of warmings of the form

`"export <> (imported as 'wasm') was not found in <>`

**Comment by CryZe** [comment]
What operating system are you on, also what are the browser versions? Also did you compile it yourself or is this when visiting https://one.livesplit.org?

**Comment by wooferzfg** [comment]
Seems like this is happening in our CI now as well: https://github.com/LiveSplit/LiveSplitOne/runs/635683262?check_suite_focus=true#step:17:124

**Comment by wooferzfg** [comment]
I think this could be related to v0.2.61 of wasm-bindgen.

The difference in the generated bindings seems to be in `livesplit_core.js`, which normally has a bunch of exports but now only has these two lines:
```
import * as wasm from "./livesplit_core_bg.wasm";
export * from "./livesplit_core_bg.js";
```

**Comment by CryZe** [comment]
Okay, so the problem seems to be that there's now a `livesplit_core_bg.js` which didn't exist before. In our bindings that we generate (on top of the wasm bindgen generated ones) we do this:
```ts
import * as wasm from "./livesplit_core_bg";
```
which is now ambiguous. I'll prepare a PR.
