### ISSUE TITLE
Add a Share dialog

### ISSUE THREAD

**Issue by hallcristobal** [LiveSplit/LiveSplitOne#35]
Exactly the same as LiveSplit, just a dialog to share and export as different formats.

**Comment by CryZe** [comment]
We may want to do this differently considering we have the "Run Selection View" and "Layout Selection View" now (well, for now we only have the sidebar for them). So we likely want to have sharing the part of the Run Selection View where you choose to upload a run to splits.io, speedrun.com, Twitter, ...

**Comment by CryZe** [comment]
What do we even envision here? We have an "export button" now in the splits view. Is there a lot more we want out of it, or is this issue basically done now?

![https://i.imgur.com/4kZ2GGE.png](https://i.imgur.com/4kZ2GGE.png)

**Comment by wooferzfg** [comment]
I think the idea here was to have the ability to share to other places (such as Twitter or imgur). I think we'd want to put those under the Export button rather than making a new Share dialog though, so I'm not sure if this issue makes sense anymore.

**Comment by CryZe** [comment]
I'll close this in favor of issues about actual indivudual export options (such as submitting to speedrun.com, Twitter, ...).
