### ISSUE TITLE
Hotkey Buttons sometimes don't unregister properly

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplitOne#357]
It seems like sometimes they keep they keep listening for buttons. It's not yet clear to me how to get this to happen in a reproducible manner. It happens fairly randomly.

**Comment by wooferzfg** [comment]
`setState` is asynchronous, so it's possible that the state isn't updated yet when we try to remove the listener? We could just set the listener and interval as instance variables like [we do for `AutoRefresh`](https://github.com/LiveSplit/LiveSplitOne/blob/master/src/util/AutoRefresh.tsx#L10).

**Comment by wooferzfg** [comment]
Though we check `this.state.listener != null` when deciding whether to show the full screen overlay, so I'm not really sure how you'd be able to run into any issues with that.

**Comment by CryZe** [comment]
I found at least one way to replicate it:

![https://i.imgur.com/Etfp7Vd.gifv](https://i.imgur.com/Etfp7Vd.gif)

I assign space to one of them, and then space collide on the other. Since the button is in focus, the spacebar also clicks on the button. That likely has something to do with it.

**Comment by wooferzfg** [comment]
Oh yeah, that makes sense. We should fix the hotkey button to only add the listener and interval if they don't already exist.
