### ISSUE TITLE
Improve Mobile Layout

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplitOne#38]
As long as we don't have mobile apps, the web version is the way to go, so we should improve the Mobile Layout. 

- [x] Layout Renderer
- [ ] Run Editor
- [ ] Layout Editor
- [ ] Settings

**Comment by LegendofzeldaLF** [comment]
Yes you guys should SO make a Mobile App for this and I will pay money (from $0-$10) for a App like that because I don't have a computer to use

**Comment by thisisdark** [comment]
This can definietly be done. However before anything else is done, we need the ability to be able to tap anywhere on the screen to end the current segment. The button is WAY to small to hit during a run.

**Comment by wooferzfg** [comment]
Specifically, the biggest things that need improvement are the Splits Editor, Layout Editor, and the Settings. These should be usable without having to scroll horizontally.
