### ISSUE TITLE
"wasm-bindgen" throwing error on build:core installation step on Manjaro

### ISSUE THREAD

**Issue by henriquelalves** [LiveSplit/LiveSplitOne#384]
Trying to build the project on a Manjaro.
All build steps run well until `npm run build:core`; than I receive the following error:

```
/bin/sh: wasm-bindgen: command not found
child_process.js:650
    throw err;
    ^

Error: Command failed: wasm-bindgen livesplit-core/target/wasm32-unknown-unknown/release/livesplit_core.wasm --out-dir src/livesplit-core
```

**Comment by CryZe** [comment]
This means wasm-bindgen is not in your PATH, did you follow the build instructions? https://github.com/LiveSplit/LiveSplitOne#build-instructions

**Comment by henriquelalves** [comment]
I did, but my bad; it was actually a problem with Rustup installing the binaries in the wrong path. I'm closing this issue!
