### ISSUE TITLE
Opening Files sometimes just doesn't do anything

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplitOne#43]
I'm not sure what causes this, but at least in Chrome the file dialog sometimes just doesn't call its "success" event.

**Comment by CryZe** [comment]
I honestly have no idea how to resolve this properly. It seems like Chrome garbage collects the input element that we use for the file open dialog, because it is not part of the DOM and thus unused. So the onchange event never happens, as the element just straight up doesn't exist anymore. Hooking the element as an invisible element into the DOM could theoretically work, but there is no way to tell that the dialog was cancelled, so we have no reliable way of removing these elements again. A solution could be to just reuse the same invisible element over and over. We could possibly marry this with #97

**Comment by CryZe** [comment]
Alright, so I fixed the Chrome bug. It's unclear whether Android and iOS still have problems opening files, so I'll keep this open until I tested it.

**Comment by wooferzfg** [comment]
Is there a good way to test this? (I have an Android phone)

**Comment by CryZe** [comment]
Considering the bug has been fixed and no one reported an issue on Android since, I'll consider this fixed for now.
