### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by 3top1a** [LiveSplit/LiveSplitOne#436]
[kenobi@hell LiveSplitOne]$ npm run build:core

> livesplit@1.0.0 build:core /home/kenobi/Downloads/LiveSplitOne
> node buildCore.js

    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `/home/kenobi/Downloads/LiveSplitOne/livesplit-core/target/debug/bindings`
warning: use of deprecated type alias `image::png::PNGEncoder`: Use `PngEncoder` instead
   --> src/run/parser/llanfair.rs:249:20
    |
249 |                 if png::PNGEncoder::new(&mut buf2)
    |                    ^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default

warning: use of deprecated type alias `image::png::PNGEncoder`: Use `PngEncoder` instead
   --> src/run/parser/llanfair2.rs:133:5
    |
133 |     png::PNGEncoder::new(&mut *buf)
    |     ^^^^^^^^^^^^^^^^^^^^

warning: use of deprecated type alias `image::png::PNGEncoder`: Use `PngEncoder` instead
   --> src/run/parser/llanfair_gered.rs:118:9
    |
118 |         png::PNGEncoder::new(&mut *tag_buf)
    |         ^^^^^^^^^^^^^^^^^^^^

warning: use of deprecated type alias `image::hdr::HDRAdapter`: Use `HdrAdapter` instead
  --> src/settings/image/shrinking.rs:19:29
   |
19 |         ImageFormat::Hdr => hdr::HDRAdapter::new(cursor)?.dimensions(),
   |                             ^^^^^^^^^^^^^^^^^^^^

warning: use of deprecated type alias `image::png::PNGEncoder`: Use `PngEncoder` instead
  --> src/settings/image/shrinking.rs:51:9
   |
51 |         png::PNGEncoder::new(&mut data).encode(
   |         ^^^^^^^^^^^^^^^^^^^^

warning: 5 warnings emitted

    Finished release [optimized] target(s) in 0.21s
/bin/sh: wasm-bindgen: command not found
child_process.js:655
    throw err;
    ^

Error: Command failed: wasm-bindgen livesplit-core/target/wasm32-unknown-unknown/release/livesplit_core.wasm --out-dir src/livesplit-core
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at Object.<anonymous> (/home/kenobi/Downloads/LiveSplitOne/buildCore.js:20:1)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  status: 127,
  signal: null,
  output: [ null, null, null ],
  pid: 47856,
  stdout: null,
  stderr: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! livesplit@1.0.0 build:core: `node buildCore.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the livesplit@1.0.0 build:core script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kenobi/.npm/_logs/2020-10-17T12_12_33_013Z-debug.log
[kenobi@hell LiveSplitOne]$ nano /home/kenobi/.npm/_logs/2020-10-17T12_12_33_013Z-debug.log

LOG: 
[2020-10-17T12_12_33_013Z-debug.log](https://github.com/LiveSplit/LiveSplitOne/files/5395604/2020-10-17T12_12_33_013Z-debug.log)

OS: manjaro
Kernel: 5.8.11-1-MANJARO

**Comment by 3top1a** [comment]
I ran all of the steps many times, but everytime I got this error.

**Comment by CryZe** [comment]
> /bin/sh: wasm-bindgen: command not found

This is the problem. You need to install wasm-bindgen like it says in the README:
```
cargo install wasm-bindgen-cli
```

**Comment by 3top1a** [comment]
https://stackoverflow.com/questions/61767863/wasm-bindgen-command-not-found-even-though-wasm-pack-is-installed-0-8-1

The last answer worked for me. (by Marcin)

**Comment by CryZe** [comment]
I assume it isn't in the PATH then. Glad you figure out a workaround though. 👍
