### ISSUE TITLE
Cannot run "npm run build:core"

### ISSUE THREAD

**Issue by thouu** [LiveSplit/LiveSplitOne#437]
Errors are showing up when I try to run "npm run build:core" during the building instructions. It says that it's probably not an issue with npm, so I'm posting it here.

[Here's a link to the logs](https://pastebin.com/Q0VgJLFm)

**Comment by wooferzfg** [comment]
Looks like the `wasm-bindgen` command isn't being found. Did `cargo install wasm-bindgen-cli` run successfully?

**Comment by thouu** [comment]
I reinstalled wasm-bindgen and there were no errors when installing, and I don't remember there being any errors when I was installing it the first time. ([logs](https://pastebin.com/trTfNfjJ))

Running "npm run build:core" still doesn't seem to be working though.

**Comment by CryZe** [comment]
wasm-bindgen needs to be in your PATH. Make sure you can manually invoke it.

**Comment by thouu** [comment]
> `wasm-bindgen` needs to be in your `PATH`. Make sure you can manually invoke it.

How do I make sure that `wasm-bindgen` is in my `PATH`? And how would I find out I can manually evoke it?

I apologize, I usually just use things like pacman and yay when installing software, not used to compiling things like this, especially with Rust.

**Comment by DarkRTA** [comment]
`export PATH="$HOME/.cargo/bin:$PATH"`

**Comment by thouu** [comment]
Running 'export PATH="$HOME/.cargo/bin:$PATH"' in the LiveSplitOne directory, reinstalling `wasm-bindgen`, running `npm run build:core`, and then running `npm start` worked, and fixed it. Thank you all!
