### ISSUE TITLE
Introduce changing the layout height

### ISSUE THREAD

**Issue by LegendofzeldaLF** [LiveSplit/LiveSplitOne#46]
So Can You Guys Make It So You Can Zoom Out And In? I Can Barley See Any of My Splits And I Would Love It If We Could Be Able To Zoom Out And In To See More Of Our Splits. Thanks!

**Comment by emoon** [comment]
I'm not sure if this is the case fore you but the way I solve this is to use the web version and simply zoom  in the browser window. While this isn't perhaps ideal it works pretty good.

**Comment by CryZe** [comment]
Actually modifying this is in at least parts blocked by livesplit-core, which has no notion of layout size at the moment. In addition it's not quite clear yet when to just use the browser's size vs. a fixed size chosen by the layout.

**Comment by CryZe** [comment]
I think we should try experimenting with at least horizontally being able to change the layout width (without any livesplit-core support initially, just a setting in LiveSplit One itself).

**Comment by CryZe** [comment]
Alright so you can horizontally stretch the layout now. So I changed the title to tracking the ability to resize vertically as well.

I think this should actually not be too hard. We just need to calculate by how much we need to multiply each "vertical size" such as font sizes and co. by to achieve a certain height.
