### ISSUE TITLE
Prevent the page from closing during a run.

### ISSUE THREAD

**Issue by TheEssenceOfDarkness** [LiveSplit/LiveSplitOne#47]
So here is the deal. I was 2 minutes ahead of my PB, until I hit the fucking back button on my phone by mistake. If there was a message that popped up asking me if I wanted to close the page, I would not have lost that run.

Edit: I apologize for the slightly hateful tone. This was written after I just lost the run.

**Comment by CryZe** [comment]
I think we also want to keep the timer running if you actually close the tab. It'll just recover the information via local storage then. Unfortunately that might be less accurate, as that is prone to clock synchronization errors, but I think we can reduce that problem through manual atomic clock synchronization. (Actually idk if that is even possible to do via HTTP)

**Comment by TheEssenceOfDarkness** [comment]
I looked through the issues, and this appears to be very similar to #26
