### ISSUE TITLE
im new too linux so i prob have a stupid question none of the other solutions work

### ISSUE THREAD

**Issue by nimnim111** [LiveSplit/LiveSplitOne#494]
Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `/home/nimnim/LiveSplitOne/livesplit-core/target/debug/bindings`
   Compiling cfg-if v1.0.0
   Compiling scopeguard v1.1.0
   Compiling lazy_static v1.4.0
   Compiling bumpalo v3.5.0
error[E0463]: can't find crate for `core`
  |
  = note: the `wasm32-unknown-unknown` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `cfg-if`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `core`
  |
  = note: the `wasm32-unknown-unknown` target may not be installed

error[E0463]: can't find crate for `core`
  |
  = note: the `wasm32-unknown-unknown` target may not be installed

error: aborting due to previous error

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
For more information about this error, try `rustc --explain E0463`.
error: build failed
child_process.js:669
    throw err;
    ^

Error: Command failed: cargo build -p cdylib --features wasm-web --target wasm32-unknown-unknown --release
    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at Object.<anonymous> (/home/nimnim/LiveSplitOne/buildCore.js:12:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! livesplit@1.0.0 build:core: `node buildCore.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the livesplit@1.0.0 build:core script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nimnim/.npm/_logs/2021-01-26T19_18_14_217Z-debug.log

**Comment by CryZe** [comment]
You need to run `rustup target add wasm32-unknown-unknown`. This is part of the README, make sure to follow all the steps.

**Comment by nimnim111** [comment]
THANKS
