### ISSUE TITLE
Issues compiling build:core

### ISSUE THREAD

**Issue by tdeeb** [LiveSplit/LiveSplitOne#525]
System Info:
```
OS: Linux Mint 20.1 Ulyssa
npm version: 7.7.5
cargo version: 1.51.0
rustup version: 1.23.1 (rustc: 1.51.0)
```
Hi, I'm having trouble compiling LiveSplitOne on one of my machines. I have already successfully compiled it on another machine running same OS a few days ago, so I'm puzzled why it's not working on that machine. I need to build locally to control LiveSplitOne from my WebSocket server.

I followed all build instructions down to the dot, but `npm run build:core` consistently fails. cargo is in my path, and I have cleaned out my cache and cargo registry, and completely deleted and recloned the repository several times to no avail. I've attached the error logs from a build, which you can find below.

[Logs.txt](https://github.com/LiveSplit/LiveSplitOne/files/6219221/Logs.txt)

It just can't seem to compile the `js-sys` library, and it appears that several WebAssembly types are unavailable. I have installed the `wasm32-unknown-unknown` target and reinstalled `wasm-bindgen-cli` 20+ times by now, so I'm not sure what to do next. I have cross-checked my settings across machines and I can't find any issues on the machine that the build fails on.

Thanks in advance for your help!

**Comment by CryZe** [comment]
This seems to be tracked here: https://github.com/rustwasm/wasm-bindgen/issues/2508

**Comment by CryZe** [comment]
This seems to be fixed in the latest version of syn: https://github.com/dtolnay/syn/issues/1003

Can you run `cargo update` and try it again?

**Comment by CryZe** [comment]
They implemented a fix directly in wasm-bindgen that fixes this problem. Since then we ran another CI build here and that completed successfully. So this should definitely be fixed after running `cargo update` now.
