### ISSUE TITLE
Integrate LiveSplit One into OBS Studio on a Linux host

### ISSUE THREAD

**Issue by Dev2ZooF** [LiveSplit/LiveSplitOne#529]
Hi,

I switched from windows months ago and I am now able to stream some speedrunning content.
To do so, I wanted to setup LiveSplit with OBS Studio but I discovered that it's sadly not as simple as I thought.

In my use case, I need to be able to show on my stream what's going on with LiveSplit One.
To do so, I use the [obs-linuxbrowser](https://github.com/bazukas/obs-linuxbrowser) plugin.
The problem is that I seem to be unable to configure LiveSplit One with that embedded browser because all pop-up prompted features won't work.
For instance, if I click the Import button on the splits settings screen, nothing happened and I can't import my split file.

This plugin allow me to pass a JS script to the browser, so I wonder if there are some functions I can call to pass any configurations (split file, layout file and maybe autosplitter settings if possible).
Or maybe is there a simple way to do what I want and I dont see it now ?

Thanks for reading.

**Comment by CryZe** [comment]
Does this work for your use case? https://github.com/CryZe/obs-livesplit-one

**Comment by Dev2ZooF** [comment]
Oh yes, so sorry I didn't saw this plugin, it's really neat!!
Thank you so much.

I know it's not related to this topic but is it possible to setup an autosplitter with this plugin ?

Anyway, that solves my problem, thanks again.

**Comment by CryZe** [comment]
We are currently working on a whole new auto splitting system for LiveSplit One. It's not really ready yet, so it's not available in the plugin until it is.
