### ISSUE TITLE
Best Segment Time incorrect when inserting splits via Editor

### ISSUE THREAD

**Issue by hallcristobal** [LiveSplit/LiveSplitOne#55]
LiveSplit/livesplit-core#63

**Comment by CryZe** [comment]
![screenshot_661](https://user-images.githubusercontent.com/12072058/28219389-cf77e3cc-6889-11e7-977f-313e59279eb5.png)
[Both LSS files Side By Side](https://www.diffchecker.com/8v6r6bKf)
