### ISSUE TITLE
The keybinds do not save when changing them

### ISSUE THREAD

**Issue by ValerieWasTaken** [LiveSplit/LiveSplitOne#575]
Hello, 
recently I moved to a new computer, and one of the things I did is setup LSO again, but when I tried to update my keybinds, they didn't save and returned to the default ones. Here's a video(i'm sorry for the garbo quality of it :/ ): 

https://user-images.githubusercontent.com/87026073/124619160-b2138e80-de78-11eb-9b48-7bcc622549ae.mp4

**Comment by CryZe** [comment]
I'm able to reproduce this as well. I'll look into it.

**Comment by ValerieWasTaken** [comment]
Alright, thank you
