### ISSUE TITLE
Increase Padding around App Icon

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplitOne#579]
When you save the site as an app, it uses one of many auto generated icons. At the moment this icon has way too little padding around it. We might want to increase the padding in the original image (which may negatively impact other uses of the icon), or look into whether our webpack plugin is configurable in some way.

![image](https://user-images.githubusercontent.com/1451630/125773380-eaba290e-f13d-4ec3-a838-740213b9672a.jpeg)

**Comment by shenef** [comment]
You could add a maskable icon. (https://web.dev/maskable-icon/)
There is additional documentation here: https://w3c.github.io/manifest/#icon-masks

**Comment by CryZe** [comment]
Seems like they have an open PR here: https://github.com/itgalaxy/favicons/pull/323

**Comment by WebSnke** [comment]
Another way to resolve this issue would be to use "apple-touch-icon" in the HTML file.
I would like to solve this problem this way myself but I don't know how I would design the icon itself.

`<link rel="apple-touch-icon" href="/path/to/icon.png">`
