### ISSUE TITLE
Figure out how to stabilize the framerate more

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplitOne#64]
It's not really bad, but I think we should be using requestAnimationFrame() or something, but last time I tried it, it was super janky, so we should look into this more.

**Comment by CryZe** [comment]
Our Frame Time is a consistent 1.5ms, so we should be able to get a consistent 650+ FPS without any drops.

**Comment by CryZe** [comment]
That's what the setInverval(30Hz) that we are doing is looking like in Chrome's Frame Rate meter: ![https://i.imgur.com/tw9fk2e.png](https://i.imgur.com/tw9fk2e.png)

**Comment by CryZe** [comment]
Twitch in comparison looks like this ![https://i.imgur.com/AxFMcNX.png](https://i.imgur.com/AxFMcNX.png)

Why is it 50FPS instead of 60??? But at least it's 100% stable.

**Comment by TheEssenceOfDarkness** [comment]
I decided to look into this a bit more, and it seems the instability was caused by your monitor running at 50hz. On a 60hz monitor, it is actually quite stable.
![screenshot_2018-02-19_21-09-00](https://user-images.githubusercontent.com/15368682/36404595-921bcce0-15b9-11e8-9806-7d768277a7c6.png)
