### ISSUE TITLE
Real LiveSplit as a program for other platforms. Not a browser Version or OBS Plugin. A real program

### ISSUE THREAD

**Issue by Kastilol** [LiveSplit/LiveSplitOne#655]
It sucks that other platforms has to use a version which isn't as good as the version that only exists for windows

**Comment by DarkRTA** [comment]
this is currently a work in progress and is very close to having a public beta release

**Comment by CryZe** [comment]
Yeah we are actively working on this. There's a bunch of cleanup and refactoring passes that need to happen before it can be released, but it's all going very well.
