### ISSUE TITLE
Look into immediate abort mode for panicking

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplitOne#656]
Currently the WASM file we ship contains a lot of panic messages, despite us never showing those anywhere. You can compile core with a nightly only feature that drops all the panic messages and just immediately aborts. This is likely what we want. It's slightly unclear if this also works with std, but we should definitely look into it.

**Comment by DarkRTA** [comment]
We may want to leave them in for debug builds as last time i checked, they do show up in the browser's console.

**Comment by CryZe** [comment]
They don't. `wasm32-unknown-unknown` doesn't know anything about the web. However you can use the [`console_error_panic_hook`](https://crates.io/crates/console_error_panic_hook) crate to hook the panics up to the JS console. This may be worth looking into for debug builds.

**Comment by CryZe** [comment]
This has been implemented.
