### ISSUE TITLE
Manual Game Time on Browser/Desktop/OBS versions? 

### ISSUE THREAD

**Issue by jB0ne90** [LiveSplit/LiveSplitOne#678]
Hello!

M1 user here! Is there currently a way of doing Manual Game Time in either the Browser, Desktop or OBS version of One? 

If so, any pointers? 😅

Keep up the great work!

**Comment by DarkRTA** [comment]
this is a duplicate of #364

**Comment by CryZe** [comment]
I'm working on Manual Game Time support now, should be available very soon. However I'll close this as a duplicate, the work is tracked in the issue mentioned by Dark.
