### ISSUE TITLE
The 5MB localStorage quota may cause issues with saving splits.

### ISSUE THREAD

**Issue by DarkRTA** [LiveSplit/LiveSplitOne#70]
As a lot of you may already know, `localStorage` normally has a quota of 5MB, (can vary across browsers), and attempting to store more than that limit will result in an error. In Firefox and Opera, this limit can be raised as needed by the user, but other browsers have to deal with this limit. Currently LiveSplit One is saving and loading splits from `localStorage`, and split files like to grow when icons are added and attempts are recorded. This will cause issues when saving, meaning users will eventually have to start importing and exporting their splits in order to continue using them.

**Comment by TheEssenceOfDarkness** [comment]
There are a few ways to remedy this problem such as removing icons from the splits, or clearing the run history.

**Comment by wooferzfg** [comment]
I think we want to shrink icons (in both LS and LSO) if they're above a certain size when setting them in the Splits Editor or loading splits.

**Comment by TheEssenceOfDarkness** [comment]
I say shrinking them to 64x64 is a good balance between icon quality and file size, that way they still look nice when displayed on the detailed timer.

**Comment by hallcristobal** [comment]
Shrinking them is ideal, compressing and then shrinking less is also good. 
If I remember correctly CryZe went to implement image resizing and it made the final library massive, so a way to do it without as much overhead would be the best.

**Comment by hallcristobal** [comment]
LiveSplit/livesplit-core#47

**Comment by CryZe** [comment]
We now do image shrinking, so this is less of an issue now. We could look into compressing the splits file in local storage, but I think this is mostly a non-issue anymore until we potentially store multiple splits files via the Run Selection View #189

**Comment by CryZe** [comment]
We can also use the native file system api to get raw access to the user's file system:
https://web.dev/native-file-system/

**Comment by CryZe** [comment]
Seems like IndexedDB allows storing MUCH more data (hundreds of megabytes even) without any problem (or even asking?! why does the browser not limit this?). So switching to IndexedDB should resolve this issue entirely.
