### ISSUE TITLE
Show a list of installed fonts

### ISSUE THREAD

**Issue by GalaxyKoala** [LiveSplit/LiveSplitOne#709]
I know you can customize the font of the timer, text, etc., but is there a complete list of all the fonts available in LS One that I could look at? Just curious

**Comment by DarkRTA** [comment]
livesplit one can use ant font available on your system

**Comment by GalaxyKoala** [comment]
Ok, thanks

**Comment by CryZe** [comment]
There is a new API where browsers can enumerate the fonts that are installed on the system. I'll eventually look into adding that.
