### ISSUE TITLE
Save / Export does not save split times

### ISSUE THREAD

**Issue by r-wettstaedt** [LiveSplit/LiveSplitOne#71]
#### Steps to reproduce the issue

1.  Open https://livesplit.github.io/LiveSplitOne, I recommend doing this in a private browser window so your localStorage does not get overwritten
2. Finish a run, even if it's only the default run with one split so you have split times
3. Save or export the file file
4. Refresh the tab
5. Import your savefile

#### What's the expected result?

- On refreshing the tab in (4.) I expect the split times to be included so I can compare my next run to them
- Same goes for the exported xml in (5.)
- When I download a sample xml from splits.io the split times are actually included in the xml file

#### What's the actual result?

- On refreshing the tab in (4.) the restored xml in the localStorage does not include the split times generated in (2.)
- Same goes for the exported xml in (5.)

#### Additional details / screenshot

This might be an issue with livesplit-core instead of LiveSplitOne

**Comment by TheEssenceOfDarkness** [comment]
This is actually resolved in #68
