### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by ThatGuyCalledJesse** [LiveSplit/LiveSplitOne#750]
Whenever I run NPM install this error pops up:
`npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'favicons@7.0.1',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'favicons-webpack-plugin@6.0.0-alpha.1',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'html-inline-script-webpack-plugin@3.1.0',
npm WARN EBADENGINE   required: { node: '>=14.0.0', npm: '>=6.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'mocha@10.0.0',
npm WARN EBADENGINE   required: { node: '>= 14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'sass-loader@13.1.0',
npm WARN EBADENGINE   required: { node: '>= 14.15.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'selenium-webdriver@4.5.0',
npm WARN EBADENGINE   required: { node: '>= 14.20.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'source-map-loader@4.0.1',
npm WARN EBADENGINE   required: { node: '>= 14.15.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.

added 903 packages, and audited 904 packages in 8s

126 packages are looking for funding
  run `npm fund` for details

1 critical severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for `details.``

I've done what it says but nothing works, thanks to this I also can't run the program.

**Comment by wooferzfg** [comment]
Make sure you're using Node 18.

**Comment by ThatGuyCalledJesse** [comment]
When trying to install node18 it gives an error

``dpkg: error processing archive /var/cache/apt/archives/nodejs_18.12.1-deb-1nodesource1_amd64.deb (--unpack):
 trying to overwrite '/usr/include/node/common.gypi', which is also in package libnode-dev 12.22.9~dfsg-1ubuntu3
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Selecting previously unselected package yarn.
Preparing to unpack .../yarn_1.22.19-1_all.deb ...
Unpacking yarn (1.22.19-1) ...
Errors were encountered while processing:
 /var/cache/apt/archives/nodejs_18.12.1-deb-1nodesource1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)``

**Comment by wooferzfg** [comment]
Try uninstalling Node 12 first, and then installing Node 18?
