### ISSUE TITLE
Submenus in Sidebar

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplitOne#77]
The Sidebar is beginning to get really cluttered. I'd prefer to group together the actions available in the sidebar and have a submenu for each one of them that shows the actual actions, kind of like the right click menu in the original LiveSplit.

**Comment by CryZe** [comment]
We should prioritize this now that we always show it.

**Comment by wooferzfg** [comment]
Any ideas for what the groupings should be? The original LiveSplit still has quite a lot of menu options.
![UltifLImCo](https://user-images.githubusercontent.com/8262173/72671287-8b0b9780-3a0d-11ea-8359-9a7872a3016e.png)

**Comment by CryZe** [comment]
I'd just condense the splits and the layout stuff into their own submenus for now.
