### ISSUE TITLE
Autosave split option

### ISSUE THREAD

**Issue by Gamebuster19901** [LiveSplit/LiveSplitOne#789]
In the web version ([one.livesplit.org](https://one.livesplit.org/)), splits are not automatically saved. I lose hours worth of splits if I forget to press [splits] -> [save].

If there was an option to enable auto saving after the end of every attempt that would be great.

**Comment by CryZe** [comment]
It's something I definitely want to look into at some point, maybe even soon.

**Comment by chrissantamaria** [comment]
+1, interested in this and would be happy to help implement on the web side (assuming development effort is still going into this repo).

Any thoughts on what the ideal UX of that would look like? Settings toggle for autosaving could be nice, but maybe even just a secondary save button surfaced on the main splits UI when there's pending changes would work as well.

From a livesplit-core perspective, when are there pending changes to save? After a completed run is likely the most obvious one, but do new gold splits count as well?

**Comment by Gamebuster19901** [comment]
> +1, interested in this and would be happy to help implement on the web side (assuming development effort is still going into this repo).

![image](https://github.com/LiveSplit/LiveSplitOne/assets/7155747/298eb794-acb0-427b-bfbe-0763345c4ac0)

Literally just this would work as a temporary solution

https://stackoverflow.com/a/7317311/6047804

**Comment by CryZe** [comment]
@Gamebuster19901 It already does that.

**Comment by wooferzfg** [comment]
Autosaving layouts would be great as well. The "leave site" popup currently doesn't come up for layouts, so it's even easier to lose your data.

**Comment by CryZe** [comment]
This is blocked by https://github.com/LiveSplit/livesplit-core/issues/807
