### ISSUE TITLE
Plugin system

### ISSUE THREAD

**Issue by jakzo** [LiveSplit/LiveSplitOne#798]
Are there any plans for a plugin system (like the main Livesplit's components)? I recently [forked this repo](https://github.com/LiveSplit/LiveSplitOne/compare/master...jakzo:LiveSplitOne:master) to make running my game easier (I'm using it with the Quest 2 standalone VR headset) and while some changes should stay in the fork it would be nice if I didn't have to have the fork diverge so far for things like autosave splits on quit.

**Comment by CryZe** [comment]
Can you elaborate what exactly you would need upstreamed from your fork? For example we will have auto saving later today.

**Comment by CryZe** [comment]
I'll close this for now, please open issues for the individual things you still want upstreamed. Auto saving is merged now.

**Comment by jakzo** [comment]
Nice. As far as I know, neither I nor anyone else have been using my fork for a while so I'm not in a rush to implement these but here are the things I added in my fork for reference:

- Auto load premade layout with levels for the game I was running (Bonelab)
- Remember last used websocket IP and autoconnect on startup (with interval retry)
- Automatically switch to game time when timer starts
- I hosted the fork on an HTTP page (not HTTPS) so that it could connect to the headset's IP without being stopped by browser security

**Comment by CryZe** [comment]
> Remember last used websocket IP

This is a thing now. I'll look into auto connect / reconnect.

> Automatically switch to game time when timer starts

I'll make it so it remembers the timing method after reloading the page.

> I hosted the fork on an HTTP page

Localhost is nowadays reachable from https again, but yeah I don't think http is something we'll do in the official version.

> Auto load premade layout with levels for the game I was running (Bonelab)

Can you explain how this is different from just opening LiveSplit with the most recent splits still being open? Or rather, what exactly is actionable for us here?

**Comment by jakzo** [comment]
> Localhost is nowadays reachable from https again, but yeah I don't think http is something we'll do in the official version.

Livesplit was actually running on a computer or phone while the game (with a mod to host a websocket autosplitter server) was running on the headset which is why I needed HTTP to connect to a local network IP and not localhost.

> what exactly is actionable for us here?

Nothing really. I added that as a convenience for people running the game to not have to set it up for the game themselves. I don't think that should be added to the core, was just mentioning all the things I added in the fork.

**Comment by CryZe** [comment]
> why I needed HTTP to connect to a local network IP and not localhost.

Yeah that's so unfortunate that they don't allow this anymore. I'm somewhat looking into therun.gg support, so maybe long term going through a website like that would help with that (at least with therun.gg it wouldn't be the WebSocket protocol though).

I opened two issues for the rest: #920  #919
