### ISSUE TITLE
Centered Title with Game Icon isn't really centered

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplitOne#80]
The name of the game is too far right: 
![https://i.imgur.com/EP6w37M.png](https://i.imgur.com/EP6w37M.png)

I'm not really sure if the second line is correct either.

**Comment by hallcristobal** [comment]
This is more of a "Not left aligned when set to 'Auto' or 'Left'" 
Observed:
![screenshot_75](https://user-images.githubusercontent.com/12072058/39893143-e189a0fe-5470-11e8-8d9b-b3b439f77776.png)
![screenshot_76](https://user-images.githubusercontent.com/12072058/39893144-e19a4d00-5470-11e8-85e8-2aa518b7e914.png)

Expected:
![screenshot_77](https://user-images.githubusercontent.com/12072058/39893229-1c02fc4e-5471-11e8-8ffb-bb63c87ca56e.png)
[No "No Icon" + "Left Align" option in LiveSplit 1.7.6]

**Comment by CryZe** [comment]
You are right looks like #61 regressed this.
