### ISSUE TITLE
How do I run an autosplitter?

### ISSUE THREAD

**Issue by TheCheddarCheese** [LiveSplit/LiveSplitOne#808]
on linux

**Comment by Refragg** [comment]
Hello, there has been a lot of work towards having ASR Auto splitters working under obs-livesplit-one, they already do work but with some limitations, if you don't mind these, you can grab it at https://github.com/LiveSplit/obs-livesplit-one.
Please keep in mind that it is still in development, ASL Auto splitters are currently not supported but hopefully they can be in the future.
Last thing, on Linux, the kernel does not let you read from any process memory like that, you have 2 options:
- Use the settings in obs-livesplit-one to start the game from there (it needs to be a child process of obs) 
- Run OBS as root to be able to access any process memory
You can head over to the [Speedrun Tool Development Discord](https://discord.com/invite/N6wv8pW) in #auto-splitting-v2 if you want more information. Hope you have a nice day!

**Comment by CryZe** [comment]
Normal auto splitters won't work on the web LiveSplit One version, so I'll close this.
