### ISSUE TITLE
Introduce an asm.js fallback for older browsers

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplitOne#82]
We can completely skip emscripten for this by using the wasm2asm tool.

**Comment by CryZe** [comment]
Looks like wasm2asm is absolutely not mature enough at all to handle this task. Other options include writing my own wasm-to-js tool (I already have wasm-to-rust, so wasm-to-js shouldn't be too much work) or using a simple wasm interpreter as a polyfill, which however should be way too slow to be usable in practice.

**Comment by CryZe** [comment]
To elaborate on why wasm2asm is not mature enough. Simple instructions like `f64.convert_u/i64` fail to be converted, as they are simply not implemented at this point in time: https://github.com/WebAssembly/binaryen/blob/9c2fa9247333233d3454c546677205b4a3c2e96a/src/passes/I64ToI32Lowering.cpp#L721

**Comment by CryZe** [comment]
Alright, I tested it again, and it does seem to work now. BUT... it produces a 200 MiB JS file. And it's so complex that minification through uglifyjs straight up crashes. Sooo I may need to write an uglifyjs-rs or something xD

**Comment by emoon** [comment]
Maybe it's just me but is this really worth doing? I mean how many people will use an older browser for this?

**Comment by CryZe** [comment]
I'd eventually like to have an LSO based Twitch Extension, and they require IE11 support. Other than that, probably not.

**Comment by CryZe** [comment]
Reminder: I just removed compatibility with all non-wasm Browsers in Babel. This needs to be reverted once we have an asm.js fallback.

**Comment by CryZe** [comment]
I started working on an uglifyjs-rs for fun, and it works for the most part. It turns the wasm2js output which is 150 MiB to a 9 MiB JS file. Sending that as a gzipped file over the network is 1.4 MiB, which is "okay". However it turns out that wasm2js is completely missing all the data sections at the moment, so it's not really usable yet. Also for some reason the equivalent emscripten JS file is 3.6 MiB, which is definitely smaller. Maybe we should just be using emscripten in the meantime.

**Comment by CryZe** [comment]
Switching to wasm-bindgen made this even more problematic now due to webpack doing all the wasm initialization and bundling for us. I don't think we want to continue supporting Internet Explorer in any way (even Edge is fairly problematic until it switches to Chromium due to it missing TextEncoder / TextDecoder).
