### ISSUE TITLE
Put Compile Instructions in ReadMe

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplitOne#83]
Now that emscripten is not necessary anymore, it should be much easier to compile LiveSplit One for potential contributors. However without any help through the ReadMe, it‘s still somewhat hard.

**Comment by Tagadda** [comment]
Huh, maybe I did something wrong before, but I can't get this to work...
I'm using ArchLinux. I installed rustup and npm, but I have an error : 
```
$ rustup target add wasm32-unknown-unknown                                                                                                                                                 
error: no default toolchain configured
```
Do you have a clue ?

**Comment by CryZe** [comment]
It seems like you need to do this: https://stackoverflow.com/a/46864309

**Comment by Tagadda** [comment]
Thanks !
