### ISSUE TITLE
The web version hosted with GitHub Page doesn't work

### ISSUE THREAD

**Issue by Tagadda** [LiveSplit/LiveSplitOne#84]
Hi.
I'm using Firefox 59 on Linux, and the web version hosted with GitHub Page doesn't work.

When I open https://livesplit.github.io/LiveSplitOne/ I got this in the console : 
```
Unhandled promise rejection 
TypeError: NetworkError when attempting to fetch resource.
bundle.js:11:185582
```

**Comment by CryZe** [comment]
Are you using uBlock? They have some rogue configuration that blocks WebAssembly.

**Comment by Tagadda** [comment]
Oh, OK, EasyList has something against WebAssembly ^^
Thanks, turning off uBlock Origin for the website solved this issue.

**Comment by CryZe** [comment]
Can you help me locate the exact list so I can investigate on why this is and report it to them?

**Comment by Tagadda** [comment]
This is in EasyPrivacy with this filter : 
`/.*(\/proxy|\.wasm|\.wsm|\.wa)$/$xmlhttprequest,domain=github.io|rawgit.com|reactor.cc|sickrage.ca|streamplay.to|tubetitties.com|vidfile.net`

**Comment by CryZe** [comment]
Alright, I added an error message now.
