### ISSUE TITLE
No splits appearing on chrome

### ISSUE THREAD

**Issue by whiteyfighter** [LiveSplit/LiveSplitOne#881]
It is blank when I select any of my splits on google chrome, absolutely nothing appears.

**Comment by ffyte** [comment]
Can you provide steps so that this can be reproduced?
Also what OS and version of Chrome?

**Comment by whiteyfighter** [comment]
This is happening now on other browsers, clearing history/cache seems to work (temporarily?)

**Comment by wooferzfg** [comment]
Can you upload a video of your issue here?

**Comment by whiteyfighter** [comment]
https://youtu.be/8fwE9FCWoOo

**Comment by CryZe** [comment]
Can you press F12, then go to Application -> IndexedDB -> LiveSplit -> settings and do a screenshot?
![image](https://github.com/LiveSplit/LiveSplitOne/assets/1451630/b807206a-b3d8-4935-96e9-adc9b32e5049)

**Comment by CryZe** [comment]
Exporting your splits and layout for us may help too.

**Comment by whiteyfighter** [comment]
Layout and splits file type are said to not be supported here.

<img width="1440" alt="Screenshot 2024-05-19 at 12 27 40 am" src="https://github.com/LiveSplit/LiveSplitOne/assets/169989232/aa5812a9-10b7-499d-95cb-a435b4ba7c82">

**Comment by CryZe** [comment]
Mmh yeah so as expected, your layout is 0x0 in dimensions. Not sure how that happened though. Can you try figuring out the steps you did to reproduce this? We could certainly "hack in" something that makes sure it's never 0x0, but it shouldn't have gotten there in the first place.

**Comment by whiteyfighter** [comment]
I did what I normally do, which is load the website, load any of my splits and saw that nothing is there. Same device, same internet connection, same browser. It does work temporarily when I clear cache, but then goes back to being blank. Maybe I'll see on some other browsers what causes the dimensions to mess up.

**Comment by whiteyfighter** [comment]
Would like to mention that this also happens when I try to load the website on safari, which worked fine until around early 2023.
<img width="1440" alt="Screenshot 2024-05-19 at 12 53 53 am" src="https://github.com/LiveSplit/LiveSplitOne/assets/169989232/db901b0f-944a-412e-89f3-945b20d2d126">

**Comment by CryZe** [comment]
> It does work temporarily when I clear cache, but then goes back to being blank

That's the step that's intriguing me. Is there anything in particular that makes it stop working again after you clear the cache? 

Safari being broken is almost certainly because it's out of date.

**Comment by whiteyfighter** [comment]
Okay I managed to replicate it on both brave browser and incognito tab, just from importing splits over and over until I had 17 splits (which was the one thing I recall doing when it broke in the past). Obviously when I clear the cache and history the number of splits goes back to 0, which is why it works.

Video: https://youtu.be/wYaLY_5HGgg

**Comment by CryZe** [comment]
Can you zip up all the splits files for me so I can retrace the video 1:1?

**Comment by whiteyfighter** [comment]
[Archive.zip](https://github.com/LiveSplit/LiveSplitOne/files/15366204/Archive.zip)
Think there is 19 split files.

**Comment by CryZe** [comment]
I came up with a theory of what it might be and was able to replicate it with that idea. It doesn't confirm it entirely yet, but the idea is as follows:

My assumption is that your layout has "fill with blank splits" turned off. This means that the layout shrinks in size to fit the amount of splits that you actually have. By switching between splits, the layout changes size. But because there is no actual layout, it fails recalculating the new size.

**Comment by whiteyfighter** [comment]
So do I need to change something from my end to solve this, or is it something else?

**Comment by CryZe** [comment]
I'm fixing it right now.

**Comment by CryZe** [comment]
What you can do in the meantime:

Go back here: https://github.com/LiveSplit/LiveSplitOne/issues/881#issuecomment-2118831581

and delete both `layoutWidth` and `layoutHeight` by clicking on them and then clicking the trash bin for both. Then after I fixed it, it shouldn't happen again.

**Comment by whiteyfighter** [comment]
Thanks, that fix worked
