### ISSUE TITLE
Show the latest updates in the About page

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplitOne#888]
Unlike the original LiveSplit, the web version just updates automatically in the background. This means that unless you keep up with the repository, you don't get to know about new features. I think we should query the most recently merged PRs that are tagged in a particular way to build a list of the most recent updates as part of the about page (or possibly somewhere else).

**Comment by wooferzfg** [comment]
I also noticed that with a service worker, it usually takes an additional refresh to get the latest version. Something I built into one of my projects with a service worker is a [prompt about there being a new update](https://github.com/wooferzfg/tww-rando-tracker/blob/main/src/ui/launcher.jsx#L60), and if you click on the prompt it refreshes the page. Maybe we want something similar for LSO?

**Comment by CryZe** [comment]
If that's easily possible, then yeah we should totally have that. The additional refresh is somewhat intended, as that means the website will load much quicker and the latest features aren't usually all that important, but if we can have a little toast popup, then that would be great.
