### ISSUE TITLE
The Rules are actually a weird mix of Markdown and BBCode

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplitOne#91]
It seems like most rules are using Markdown now, but https://www.speedrun.com/Portal#Inbounds and probably others are still using BBCode. I'm not entirely sure if it's an either BBCode or Markdown situation or if there's actually some mixture going on.

**Comment by CryZe** [comment]
It seems to indeed be some mix. `[section=Okok]` seems to be something BBCode-like. However I can't get actual BBCode to work `[u][b]Test[/b][/u]` renders just like that. Which is even more weird, because the Portal Inbounds rules do exactly that. So it seems like the database possibly tracks whether the rules are in legacy bbcode mode or mixed markdown mode.

**Comment by wooferzfg** [comment]
Seems like the rules are assumed to be legacy bbcode until you save them again in the speedrun.com UI, at which point they get updated to use markdown. It's weird that the API doesn't expose that though.

**Comment by CryZe** [comment]
It seems like they don't track that in their DB either though, so it's really unclear what's going on. We probably need to talk to pac or some other active dev again to see what's going on here. We could also possibly just ignore the legacy bbcode and hope people update to markdown over time.

**Comment by CryZe** [comment]
Enough changed on their side that I at least can't reproduce it anymore, so I'm closing this.
