### ISSUE TITLE
Initial install of service worker triggers "update found" message

### ISSUE THREAD

**Issue by CryZe** [LiveSplit/LiveSplitOne#913]
Apparently `controllerchange` is not quite the right event. There's `updatefound` which might be the better way:

https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration#examples

cc @wooferzfg

**Comment by wooferzfg** [comment]
Hmm, I'm not actually sure how to use this in the React code, since we need to add an event listener to the return value of `serviceWorker.register`, but the registration happens asynchronously outside of the React code: https://github.com/LiveSplit/LiveSplitOne/blob/0902aa339b5e05a63fb1a02b7c60756b321fffdc/src/index.tsx#L22

**Comment by wooferzfg** [comment]
Maybe we need to create a promise, pass the promise to the React code, and then resolve the promise based on whether the service worker has an update

**Comment by CryZe** [comment]
Yeah that's what I thought too.

**Comment by wooferzfg** [comment]
I'll try to fix this later today

**Comment by wooferzfg** [comment]
I think something like this should work:
```
const hasUpdatePromise = new Promise((resolve) => {
  if (process.env.NODE_ENV === 'production' && 'serviceWorker' in navigator) {
    navigator.serviceWorker.register('service-worker.js').then((registration) => {
      registration.addEventListener('updatefound', () => resolve(true));
    }).catch(() => resolve(false));
  } else {
    resolve(false);
  }
});
```

**Comment by wooferzfg** [comment]
I'm not actually sure that this solves our issue. It seems like `updatefound` gets called even on the initial install.

**Comment by CryZe** [comment]
Is there a way to check if the service worker "exists" and then simply ignore the event if it didn't exist?
