### ISSUE TITLE
Autocomplete boxes appear out of place

### ISSUE THREAD

**Issue by hallcristobal** [LiveSplit/LiveSplitOne#92]
When clicking on a box that creates an dropdown (i.e. Game & Category in Run Editor) they will appear away from the field itself
![screenshot_84](https://user-images.githubusercontent.com/12072058/40140876-fdc966fe-5921-11e8-9fe1-2556ee1f322d.png)

However this is corrected after a redraw when you start typing.

**Comment by CryZe** [comment]
This doesn't happen on my browser O.o

**Comment by hallcristobal** [comment]
Okay this is (partially) my fault (maybe?)

I'm using two monitors with two different resolutions (4K and 900p) and i had it on the 900p one which doesn't scale nicely on Windows, causing the offset to be skewed
