### ISSUE TITLE
Desktop version: getting stuck on loading screen

### ISSUE THREAD

**Issue by atbarry** [LiveSplit/LiveSplitOne#953]
Thanks for the development of this repo, and congrats on the new desktop build! 

After adding some necessary dependencies, I was able to get the program to start up. 
Unfortunately I encountered an issue where it gets stuck on the "Loading" screen
![image](https://github.com/user-attachments/assets/b077d141-26c9-4b00-a3db-c0045660f4b5)

The only logs that I can see are: 
``` 
** (livesplit:650326): WARNING **: 23:30:37.381: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
```
Could you please confirm if there are any additional dependencies or configurations required to resolve this issue?

Thank you!

**Comment by CryZe** [comment]
I identified the issue. A new version will be published soon.

**Comment by Gamebuster19901** [comment]
> I identified the issue. A new version will be published soon.

where

**Comment by Gamebuster19901** [comment]
This is still an issue even with #954 merged. I forked this repo and modified it so github would generate a build with the fix., I still encounter this issue.

**Comment by Gamebuster19901** [comment]
This issue has been fixed in the latest release, thanks.

**Comment by CryZe** [comment]
I didn't actually change anything regarding to this in the latest build, but maybe the previous build didn't build correctly or something.
